### ISSUE TITLE
Different values for mesh and mesh_size in UPF file

### ISSUE THREAD

**Issue by simonpintarelli** [atompaw/atompaw#4]
I have a question regarding the UPF file generated by atompaw. The values of `mesh_size` in `<PP_HEADER>` and `mesh` in `<PP_MESH>` do not correspond. QuantumEspresso v7.0, will read both, but ignore `mesh_size` if it doesn't equal `<PP_MESH mesh>`:
https://gitlab.com/QEF/q-e/blob/develop/upflib/read_upf_new.f90#L234
(In case QE was compiled with debug flags, it will throw an error)

In the example below (atompaw input from mineralscloud.com), `mesh_size` from the UPF seems to be `gridsize-1` (=699). Is the way QE is parsing the UPF from atompaw correct, i.e. that it ignores `gridsize` in `<PP_HEADER>`? 

```
Eu  63                                                          
GGA-PBE  loggrid 700 scalarrelativistic logderivrange -8 8 500  
6 5 5 4 0                                                       
5 2 1                                                           
4 3 6                                                           
0 0 0                                                           
c                                                               
c                                                               
c                                                               
c                                                               
v                                                               
v                                                               
c                                                               
c                                                               
c                                                               
v                                                               
c                                                               
c                                                               
v                                                               
v                                                               
3                                                               
2.559 2.132 2.559 2.559
n                                                               
y                                                               
2.0                                                             
n                                                               
y                                                               
2.0                                                             
n                                                               
y                                                               
2.0                                                             
n                                                               
VANDERBILT BESSELSHAPE                                          
4 0.0                                                           
2.519
2.519
2.519
2.519
2.519
2.519
2.519
2.519
ABINITOUT
default
PWSCFOUT                                                        
UPFDX  0.0125d0  UPFXMIN  -7.d0  UPFZMESH  63.0
END
0
```

**Comment by natalieawh** [comment]
Dear SimonPintarelli,
        Probably your UPF file is OK.    The Quantum Espresso interface in ATOMPAW has not been changed in many years and, in fact, we would be happy to update it with help from the Quantum Espresso developers and users.     The internal mesh used by ATOMPAW  (pwpaw.wfu.edu)  includes the origin and therefore is different from that required by the UPF format.    It is my experience that QE correctly reads the PP-MESH heading according to what is written on the line (in your example)
UPFDX  0.0125d0  UPFXMIN  -7.d0  UPFZMESH  63.0
Did you have an error in running QE?   If so what did it say?        If you are concerned about the accuracy of the calculation,  you may wish to increase the ATOMPAW grid on the second line 
GGA-PBE  loggrid 2001 scalarrelativistic logderivrange -8 8 500 
This will be the grid used be the self-consistent solver in ATOMPAW.    In constructing the UPF file, the results are interpolated on the QE - compatible grid.      Please let me know if this helps or not.     Thanks, Natalie Holzwarth.   natalie@wfu.edu
