### ISSUE TITLE
build system on intel

### ISSUE THREAD

**Issue by jzwanzig** [atompaw/atompaw#6]
Hi @mtorrent @natalieawh ,
just did a pull from github, I'm using the new Intel oneAPI compiler system (which is now free, by the way). The atompaw build system doesn't seem to work well with it, there's a problem when the system tries to compile a file that uses modules, but those modules haven't yet been built. In other words, compiling files in alphabetical order (say) fails because some of them USE modules that haven't been build yet. I don't know why this is a compile time issue, but it seems to be, and intel's documentation confirms it. This seems very inconvenient for the build system, but there it is.

Joe

**Comment by mtorrent** [comment]
Dear Joe,
I was able to reproduce your issue with intel compiler.
As I was looking for the solution, I found that an extra ":q" was present in the `configure.ac` file. I suppressed it and it seems to work again.  
Can you check?

**Comment by jzwanzig** [comment]
Hi Marc, can you be more specific about where to look? In configure.ac I see only two instances of the letter Q (no q), both in macros using "PREREQ"

Josef W. Zwanziger
Professor, Department of Chemistry
Canada Research Chair in NMR Studies of Materials
Director, Dalhousie University NMR-3 Centre
Department of Chemistry
Dalhousie University
6274 Coburg Road
P.O. Box 15000
Halifax NS  B3H 4R2
tel: +1 (902) 494-1960
fax: +1 (902) 494-1310
web: http://jwz.chem.dal.ca
***@***.***
________________________________

**Comment by mtorrent** [comment]
Looking closer, I realize that this ":q" was not present in version 4.2.0.1. So that might not be the cause of your problem. If so, I cannot reproduce your problem.
Did you use the new (ifx) or classic (ifort) version of the compiler?

**Comment by mtorrent** [comment]
No... I also used the classic one.  
So i confirm that I cannot reproduce the problem.

**Comment by jzwanzig** [comment]
Setting LTOBJEXT="o" in configure.ac builds correctly for both ifort and ifx; neither build with LTOBJEXT="lo" work. 🙁

Josef W. Zwanziger
Professor, Department of Chemistry
Canada Research Chair in NMR Studies of Materials
Director, Dalhousie University NMR-3 Centre
Department of Chemistry
Dalhousie University
6274 Coburg Road
P.O. Box 15000
Halifax NS  B3H 4R2
tel: +1 (902) 494-1960
fax: +1 (902) 494-1310
web: http://jwz.chem.dal.ca
***@***.***
________________________________

**Comment by mtorrent** [comment]
So it might be linked to your `libtool` version.  
I regularly encounter this problem and don't really know how to solve it. Most of the time it's due to an error during the configure step breaking the build.  
Did your configure script execute without any error?

**Comment by jzwanzig** [comment]
Configure step seems fine, even when it leads to a failure during build. I'm using libtool 2.4.6, for whatever that's worth.

Josef W. Zwanziger
Professor, Department of Chemistry
Canada Research Chair in NMR Studies of Materials
Director, Dalhousie University NMR-3 Centre
Department of Chemistry
Dalhousie University
6274 Coburg Road
P.O. Box 15000
Halifax NS  B3H 4R2
tel: +1 (902) 494-1960
fax: +1 (902) 494-1310
web: http://jwz.chem.dal.ca
***@***.***
________________________________
