### ISSUE TITLE
compilation failed version 4.2.0.3

### ISSUE THREAD

**Issue by samuelymei** [atompaw/atompaw#8]
When I compiled the latest version (4.2.0.3), it failed with the error message:
gfortran -DHAVE_CONFIG_H -I. -I..     -g -O2 -c -o pseudo_sub.o pseudo_sub.F90
pseudo_sub.F90:886:21:

  886 |     do ib=1,AEOrbit%norbit
      |                     1
Error: Symbol ‘aeorbit’ at (1) has no IMPLICIT type
pseudo_sub.F90:887:19:

  887 |       if (AEOrbit%iscore(ib)) then
      |                   1
Error: Symbol ‘aeorbit’ at (1) has no IMPLICIT type
pseudo_sub.F90:888:35:

  888 |         CALL expinvr(Grid,AEOrbit%wfn(:,ib),lmb)
      |                                   1
Error: Symbol ‘aeorbit’ at (1) has no IMPLICIT type
pseudo_sub.F90:889:41:

  889 |         lmb_tot = lmb_tot + lmb*AEOrbit%occ(ib)
      |                                         1
Error: Symbol ‘aeorbit’ at (1) has no IMPLICIT type
pseudo_sub.F90:890:9:

  890 |       end if
      |         1
Error: Expecting END SUBROUTINE statement at (1)
pseudo_sub.F90:891:7:

  891 |     end do
      |       1
Error: Expecting END SUBROUTINE statement at (1)

One possible solution is adding 
     USE AEatom
to the module
     MODULE pseudo_sub
in file src/pseudo_sub.F90

**Comment by mtorrent** [comment]
dear @samuelymei ,  
Thanks for the fix.  
It has been addressed in the development version and will be corrected in the next official release.

**Comment by mtorrent** [comment]
Dear @samuelymei,  
Thanks for the fix.  
It has been addressed in the development version and will be corrected in the next official release.
